#
policy_path: "/home/xinyu/Projects/Isaac/Lab_1/logs/rsl_rl/g1_rough/2025-06-04_15-49-28/exported/policy.pt"
# policy_path: "/home/xinyu/Projects/Isaac/Lab_1/logs/rsl_rl/g1_rough/2025-05-13_19-08-53/exported/policy.pt"

xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/lab1_g1_29dof_rev_1_0.xml"
# xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/lab1_g1_23dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
# simulation_dt: 0.005
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps:
  [
    100,
    100,
    100,
    150,
    40,
    40,
    100,
    100,
    100,
    150,
    40,
    40,
    300,
    300,
    300,
    100,
    100,
    50,
    50,
    20,
    20,
    20,
    100,
    100,
    50,
    50,
    20,
    20,
    20,
  ]

kds:
  [
    2,
    2,
    2,
    4,
    2,
    2,
    2,
    2,
    2,
    4,
    2,
    2,
    3,
    3,
    3,
    2,
    2,
    2,
    2,
    1,
    1,
    1,
    2,
    2,
    2,
    2,
    1,
    1,
    1,
  ]

#initial position of the robot
default_angles:
  [
    -0.20,
    0.0,
    0.0,
    0.42,
    -0.23,
    0.0,
    -0.20,
    0.0,
    0.0,
    0.42,
    -0.23,
    0.0,
    0.0,
    0.0,
    0.0,
    0.35,
    0.16,
    0.0,
    0.87,
    0.0,
    0.0,
    0.0,
    0.35,
    -0.16,
    0.0,
    0.87,
    0.0,
    0.0,
    0.0,
  ]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.25
# ang_vel_scale: 0.01
# dof_pos_scale: 0.01
# dof_vel_scale: 0.01
# action_scale: 0.01

num_actions: 21
num_obs: 72

cmd_scale: [1.0, 1.0, 1.0]
cmd_init: [0.5, 0.0, 0.0]
