#
policy_path: "/home/xinyu/Projects/Isaac/Lab_1/logs/rsl_rl/g1_rough/2025-05-08_17-02-42/exported/policy.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/g1_23dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [
    200.0, # left_hip_pitch_joint
    150.0, # left_hip_roll_joint
    150.0, # left_hip_yaw_joint
    200.0, # left_knee_joint
    20.0, # left_ankle_pitch_joint
    20.0, # left_ankle_roll_joint
    200.0, # right_hip_pitch_joint
    150.0, # right_hip_roll_joint
    150.0, # right_hip_yaw_joint
    200.0, # right_knee_joint
    20.0, # right_ankle_pitch_joint
    20.0, # right_ankle_roll_joint
    200.0, # waist_yaw_joint
    40.0, # left_shoulder_pitch_joint
    40.0, # left_shoulder_roll_joint
    40.0, # left_shoulder_yaw_joint
    40.0, # left_elbow_joint
    40.0, # left_wrist_roll_joint
    40.0, # right_shoulder_pitch_joint
    40.0, # right_shoulder_roll_joint
    40.0, # right_shoulder_yaw_joint
    40.0, # right_elbow_joint
    40.0, # right_wrist_roll_joint
  ]
kds: [
    5.0, # left_hip_pitch_joint
    5.0, # left_hip_roll_joint
    5.0, # left_hip_yaw_joint
    5.0, # left_knee_joint
    2.0, # left_ankle_pitch_joint
    2.0, # left_ankle_roll_joint
    5.0, # right_hip_pitch_joint
    5.0, # right_hip_roll_joint
    5.0, # right_hip_yaw_joint
    5.0, # right_knee_joint
    2.0, # right_ankle_pitch_joint
    2.0, # right_ankle_roll_joint
    5.0, # waist_yaw_joint
    10.0, # left_shoulder_pitch_joint
    10.0, # left_shoulder_roll_joint
    10.0, # left_shoulder_yaw_joint
    10.0, # left_elbow_joint
    10.0, # left_wrist_roll_joint
    10.0, # right_shoulder_pitch_joint
    10.0, # right_shoulder_roll_joint
    10.0, # right_shoulder_yaw_joint
    10.0, # right_elbow_joint
    10.0, # right_wrist_roll_joint
  ]

default_angles: [
    -0.20, # left_hip_pitch_joint
    0.0, # left_hip_roll_joint
    0.0, # left_hip_yaw_joint
    0.42, # left_knee_joint
    -0.23, # left_ankle_pitch_joint
    0.0, # left_ankle_roll_joint
    -0.20, # right_hip_pitch_joint
    0.0, # right_hip_roll_joint
    0.0, # right_hip_yaw_joint
    0.42, # right_knee_joint
    -0.23, # right_ankle_pitch_joint
    0.0, # right_ankle_roll_joint
    0.0, # waist_yaw_joint
    0.35, # left_shoulder_pitch_joint
    0.16, # left_shoulder_roll_joint
    0.0, # left_shoulder_yaw_joint
    0.87, # left_elbow_joint
    0.0, # left_wrist_roll_joint
    0.35, # right_shoulder_pitch_joint
    -0.16, # right_shoulder_roll_joint
    0.0, # right_shoulder_yaw_joint
    0.87, # right_elbow_joint
    0.0, # right_wrist_roll_joint
  ]
# ang_vel_scale: 1.0
# dof_pos_scale: 1.0
# dof_vel_scale: 1.0
ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.5

num_actions: 23
num_obs: 81

cmd_scale: [1.0, 1.0, 1.0]
cmd_init: [0.2, 0, 0]
